SELECT * FROM salesretails.salesretails;

-- total_no_sales--
select count(*) as total_no_sales from salesretails;
-- total sales by day--
select sale_date,sum(total_sale) as daily_sales
from salesretails
group by sale_date
order by sale_date;
-- max and min age by gender-- 
select gender,max(age) as max_age,min(age) as min_age
from salesretails
group by gender;
-- count of rows per category
select category,count(*) as category_count from salesretails
group by category;
-- count of rows per gender
select gender,count(*) as gender_count
from salesretails
group  by gender;

-- -- Sales and Revenue Analysis --
-- Total revenue generated by each product category--
select category,sum(total_sale) as total_revenue
from salesretails
group by category
order by total_revenue;
-- monthly trend of total sales over the year--
select date_format(str_to_date(sale_date,'%d-%m-%y'),'%y-%m') as sale_month,
sum(total_sale) as total_sales
from salesretails
group by sale_month
order by sale_month;
-- day of the week generates the highest sales on average--
select dayname(str_to_date(sale_date,'%d-%m-%y')) as weekday,avg(total_sale) as avg_sales
from salesretails
group by weekday
order by avg_sales desc;
-- which time of day has the highest avg sales
select 
case
when hour(sale_time) between 5 and 11 then'Morning'
when hour(sale_time) between 12 and 16 then'Afternoon'
when hour(sale_time) between 17 and 21 then'evening'
else 'Others'
end as time_of_day,
avg(total_sale) as avg_sale
from salesretails
group  by time_of_day
order by avg_sale desc;
-- avg transaction amount per customer
select customer_id,avg(total_sale) as avg_transaction
from salesretails 
group by customer_id
order by avg_transaction desc;
-- which age group spend the most on average--
select concat(floor(age/10)*10,'_',floor(age/10)*10+9) as age_group
,avg(total_sale) as avg_spending
from salesretails
group by age_group
order by avg_spending desc;
-- gender wise  spending pattern across different categories
select gender,category,sum(total_sale) as total_spending
from salesretails
group by gender,category
order by gender,total_spending desc;
-- top 5 customers by total spending--
select customer_id,sum(total_sale) as total_spending
from salesretails
group by customer_id
order by total_spending desc
limit 5;